
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 26 15:31:41 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 29;
  public static final int LBRACKET = 17;
  public static final int CHAR = 41;
  public static final int CONST = 4;
  public static final int LTEQ = 31;
  public static final int CASE = 46;
  public static final int CONTINUE = 48;
  public static final int LPAREN = 15;
  public static final int SEMI = 14;
  public static final int MINUS = 22;
  public static final int RPAREN = 16;
  public static final int AND = 32;
  public static final int LT = 30;
  public static final int OR = 33;
  public static final int BOOL = 40;
  public static final int COMMA = 37;
  public static final int QMARK = 19;
  public static final int CLASS = 49;
  public static final int INC = 35;
  public static final int DIV = 24;
  public static final int PLUS = 21;
  public static final int IF = 43;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int RBRACKET = 18;
  public static final int EQUAL = 34;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int MUL = 23;
  public static final int NUMBER = 39;
  public static final int MOD = 25;
  public static final int NEQ = 27;
  public static final int BREAK = 47;
  public static final int IDENT = 42;
  public static final int VOID = 8;
  public static final int EQ = 26;
  public static final int SWITCH = 45;
  public static final int COLON = 20;
  public static final int ELSE = 44;
  public static final int LBRACE = 12;
  public static final int POINT = 38;
  public static final int ENUM = 3;
  public static final int READ = 6;
  public static final int WHILE = 11;
  public static final int RBRACE = 13;
  public static final int EXTENDS = 50;
  public static final int PROG = 2;
  public static final int DEC = 36;
  public static final int GT = 28;
  public static final int PRINT = 5;
  public static final int DO = 10;
}

