
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Apr 21 22:10:42 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 28;
  public static final int LBRACKET = 16;
  public static final int CHAR = 40;
  public static final int CONST = 4;
  public static final int LTEQ = 30;
  public static final int LPAREN = 14;
  public static final int SEMI = 13;
  public static final int MINUS = 21;
  public static final int RPAREN = 15;
  public static final int AND = 31;
  public static final int LT = 29;
  public static final int OR = 32;
  public static final int BOOL = 39;
  public static final int COMMA = 36;
  public static final int QMARK = 18;
  public static final int INC = 34;
  public static final int DIV = 23;
  public static final int PLUS = 20;
  public static final int IF = 42;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int RBRACKET = 17;
  public static final int EQUAL = 33;
  public static final int error = 1;
  public static final int MUL = 22;
  public static final int NUMBER = 38;
  public static final int MOD = 24;
  public static final int NEQ = 26;
  public static final int IDENT = 41;
  public static final int VOID = 8;
  public static final int EQ = 25;
  public static final int COLON = 19;
  public static final int ELSE = 43;
  public static final int LBRACE = 11;
  public static final int POINT = 37;
  public static final int ENUM = 3;
  public static final int READ = 6;
  public static final int WHILE = 10;
  public static final int RBRACE = 12;
  public static final int PROG = 2;
  public static final int DEC = 35;
  public static final int GT = 27;
  public static final int PRINT = 5;
  public static final int DO = 9;
}

